### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Ldev/icerock/moko/resources/ResourceContainerKt;

### ISSUE THREAD

**Issue by a-blekot** [luca992/libphonenumber-kotlin#9]
Hi! I'm trying to create `PhoneNumberVisualTransformation` like in your sample, but I can't fix this error...

I have even applied plugin `id("dev.icerock.mobile.multiplatform-resources")` to my module, but no effect.

I also use moko-resources in my project - maybe generated classes conflicts somehow?

![Screenshot 2023-08-21 at 12 25 04](https://github.com/luca992/libphonenumber-kotlin/assets/66264959/95b2901f-c1bb-4538-97f1-35c00f1e9901)

![Screenshot 2023-08-21 at 12 29 56](https://github.com/luca992/libphonenumber-kotlin/assets/66264959/f1584cdb-009c-403a-91af-d6e7b21fd07a)

**Comment by luca992** [comment]
Hey, sorry I didn't have notifications turned on for this project. I think I may have fixed your issue a couple days after this. Maybe try re-pulling the snapshot.
